### ISSUE TITLE
It seems Set Default Row Limit Option doesn't work

### ISSUE THREAD

**Issue by talkingdotnet** [dbcli/mssql-cli#102]
I set the MSSQL_CLI_ROW_LIMIT to 1 or 0 to see any changes but not getting any 

row limit prompt. And can't seem to disable the prompt. I understand this would limit the number of rows for select statement. 

Note - I am running command prompt in administrator mode..

![set row limit issue](https://user-images.githubusercontent.com/18328337/33956137-af9954c6-e063-11e7-8dde-e74c135db76d.gif)

**Comment by amjith** [comment]
What's the behavior you intend to see when you set that ROW_LIMIT? 

When you say row limit prompt are you talking about the fact that the output table is paginated and show using the `more` pager?

Because your screen capture doesn't show a row limit prompt, so I'm wondering if I'm missing something.

**Comment by talkingdotnet** [comment]
Well, I thought that when the row limit is set to 10, only first ten records should be displayed and when set to 0, all records should be displayed (with no option for more).. No matter what value you set, there is no difference in the output. The documentation says "Set environment variable MSSQL_CLI_ROW_LIMIT to set threshold for row limit prompt. Use 0 to disable prompt." 
![set row limit issue_1](https://user-images.githubusercontent.com/18328337/33975759-a9b9b282-e0b6-11e7-96ce-3693ec0f35f3.gif)


Or, let me know if this option has a different purpose?

**Comment by amjith** [comment]
That is indeed a bug. Looks like the row_limit is ignored in the code. I'll see what I can do.

**Comment by amjith** [comment]
@talkingdotnet I've merged a PR that should enable the use of that env var. So next version should have it.

The way that feature works is that, it'll ask you to confirm to see the results if the number of rows in the result set is above the threshold you've set in the env var.

For example: If you have `MSSQL_CLI_ROW_LIMIT` set to 10 and you run a query that returns 11 rows then the client will prompt you with a question that asks `The result has 11 rows are you sure you want to see the results (y/N)?`. 

The default value for the row limit is 1000 which is set in the config file located under `C:\Users\<Username>\AppData\Local\dbcli\mssqlcli\config`. Just look for row_limit and you can change it there as well.

I hope that clarifies your question.

**Comment by abhisheksinha89** [comment]
Thanks a lot @amjith 
I've verified this fix and it should be available in our next release (v0.9.0 and above).
Closing this issue.
