### ISSUE TITLE
Cannot get required symbol EC_KEY_set_public_key_affine_coordinates from libssl 'serverInfo'

### ISSUE THREAD

**Issue by need47** [dbcli/mssql-cli#113]
I have the following libssl on my system (CentOS 7.4.1708):
/lib/libssl.so.0.9.8e*
/lib/libssl.so.10@
/lib/libssl.so.1.0.2k*
/lib/libssl.so.6@

uname -a
Linux machine 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Python 3.6.2

**Comment by pensivebrian** [comment]
Interesting. Definitely looks like an openssl-lib package issue with the version and/or configuration, but I'm unable to repro this issue on my CentOS 7.4.1708 setup, using the same openssl-lib 1.0.2k version package.

**Comment by pensivebrian** [comment]
Closing this as it seems to be a libssl configuration issue.
