### ISSUE TITLE
TRANSFER Keyword no showing 

### ISSUE THREAD

**Issue by ernesth65** [dbcli/mssql-cli#114]
ALTER SCHEMA XXX TRANSFER not showing in intellisense

**Comment by abhisheksinha89** [comment]
Thanks, we will look into this we may have missed this keyword.

**Comment by MrMeemus** [comment]
This will be added once we fully implement smart completion since this keyword requires context of the "ALTER SCHEMA" statement.

**Comment by MrMeemus** [comment]
Fixed in #132
