### ISSUE TITLE
Allow for full SQL Server connection properties

### ISSUE THREAD

**Issue by rahulballal** [dbcli/mssql-cli#118]
At the moment thee is no way to specify connection properties like `ApplicationIntent`. It would be awesome to see this in upcoming releases.

https://blogs.msdn.microsoft.com/alwaysonpro/2013/08/02/connect-to-sql-server-using-application-intent-read-only/

**Comment by abhisheksinha89** [comment]
Thanks, we plan on doing this 👍

**Comment by abhisheksinha89** [comment]
The fix went in as part of the above PR. . It will be resolved in our next release.

**Comment by abhisheksinha89** [comment]
Please update mssql-cli. It should be fixed in v0.9.0 and later. 
pip install --upgrade mssql-cli

**Comment by rahulballal** [comment]
great work @abhisheksinha89 !! Thanks
