### ISSUE TITLE
distorted query resultset

### ISSUE THREAD

**Issue by codandn** [dbcli/mssql-cli#120]
When you try to maximize the window, the query resultset table gets distorted or misaligned. When you restore down the window, it goes back to original aligned result. Only experienced  this using command prompt. No issue on powershell.

**Comment by abhisheksinha89** [comment]
Hi yes this is an issue with windows cmd prompt and we can't solve it trivially within the application. 
An easy workaround is to enter 'Ctrl+L' which clears the screen and aligns the prompt for you again after you've resized the window.
