### ISSUE TITLE
@@ variables do not get intellisense prompting but some of them get syntax highlighting

### ISSUE THREAD

**Issue by smooth1x1** [dbcli/mssql-cli#121]
Typing 'SELECT @@VERSION'  

a) whilst typing 'SELECT' we get prompts for auto-completion of the keyword.
b)Whilst typing @@VERSION there is no prompt for auto-completion of the variable name as in SSMS.

Once the full variable name @@VERSION is entering it is highlighted 

See http://www.smooth1.co.uk/installs/dbinstalls.html#7.2.3

**Comment by MrMeemus** [comment]
@smooth1x1 , I will close this issue and use #122 for reference for the overall syntax highlighting fix.
