### ISSUE TITLE
Not able to connect to google sql mysql instance

### ISSUE THREAD

**Issue by hethkar** [dbcli/mssql-cli#133]
I am trying to connect to a mysql5.6 database instance in google SQL. The ip address i am using is authorized in the google sql.
I am using the following command to connect to the instance.
mssql-cli -S instanceipaddresshere -d dbname -U user
and i paste the password after it prompts.
This is what i am getting -
`Connection did not succeed.
Error message: A network-related or instance-specific error occurred while estab
lishing a connection to SQL Server. The server was not found or was not accessib
le. Verify that the instance name is correct and that SQL Server is configured t
o allow remote connections. (provider: SQL Network Interfaces, error: 25 - Conne
ction string is not valid)
Unable to connect. Please try again`

**Comment by pensivebrian** [comment]
Hello, @hethkar. mssql-cli will not work with MySQL. mssql-cli only support working with Microsoft SQL Server. May I suggest using [mycli](https://github.com/dbcli/mycli)? Is has the same CLI experience, but works with MySQL.

**Comment by hethkar** [comment]
@pensivebrian Hey thanks for the suggestion.
