### ISSUE TITLE
Executing queries pollutes the screen with character garbage 

### ISSUE THREAD

**Issue by fhureau** [dbcli/mssql-cli#134]
Hi,
My MSSQL user is read-only and the session fails to open when I try to connect with the same credentials that I use on Server Management Studio. Could it be a privilege issue?
If so, could it please be added on the enhancements list?
Thanks a lot!

**Comment by fhureau** [comment]
I finally could connect when manually typing the password instead of pasting

**Comment by fhureau** [comment]
I could finally connect by manually typing the password instead of pasting it, and I managed to get basic queries done but my screen is fully polluted by 
![image](https://user-images.githubusercontent.com/16597934/34718415-d52301f0-f536-11e7-9bf6-809b774badd5.png)
characters whatever I do (CTRL+K / CTRL+L don't work)

**Comment by pensivebrian** [comment]
@fhureau - are you using powershell? If so, this looks similar to issue #111. Can you provide some details by running the following on the command line:

The active code page by running `CHCP` 

The python version by running `python --version`

The powershell version by running `$PSVersionTable.PSVersion`

**Comment by MrMeemus** [comment]
@fhureau, the solution I found to #111 was to toggle the font to the other font and back. Could you please give that a try and let me know if that solves your issue.

Thanks!

**Comment by MrMeemus** [comment]
@fhureau , what is your system locale and font for powershell?

**Comment by MrMeemus** [comment]
Closing as a dup of #111
