### ISSUE TITLE
ms-pydocx

### ISSUE THREAD

**Issue by internetjanitor** [dbcli/mssql-cli#143]
https://pydocx.readthedocs.io/ + https://python-docx.readthedocs.io/

**Comment by internetjanitor** [comment]
pydocx is pretty well perfect btw.  I've extended it for code blocks (using <pre>) and used adjacency css to add margin only to the outset of repeated styles (specifically +<p>).  I also remove empties or same-style (strong, etc) repeats and combine per-line <pre> repeats into contiguous blocks using regex.  Then I transform the custom <pre> tag for code blocks into <pre><code class="codeStyle"> (for a custom docx style called "Terminal") to both format indents correctly and have the option to use highlight.js later.

**Comment by OneLine-Lee** [comment]
![20180123192439](https://user-images.githubusercontent.com/8857021/35273328-2a6ab88c-0073-11e8-86dc-a0d954d3053c.png)
can anyone help me?

**Comment by pensivebrian** [comment]
@OneLine-Lee This looks like a permissions issue. You'll have to run the pip install command from an elevated command prompt.

To create an elevated command prompt, when you launch cmd.exe, try right clicking on the icon, and select the "Run as administrator". Then, run the `pip install mssql-cli` command in the elevated console.

If you continue to have issues, please create a new issue, and we can work through any install problems in that issue.

**Comment by pensivebrian** [comment]
Closing this as I don't underlying the issue or request with respect to pydocx.
