### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by chubbsm** [dbcli/mssql-cli#149]
Won't run under Windows 2008 R2 server. Gets out of memory error same as Windows 7.

Version: 0.9.0
Mail: sqlcli@microsoft.com
Home: http://github.com/dbcli/mssql-cli
master>SELECT * from sys.systables
Not enough memory.
Time: 0.062s
master>

**Comment by Jaxelr** [comment]
Guessing this is the same symptom as #98 

Would love confirmation from the team.

**Comment by pensivebrian** [comment]
Windows 2008 R2 is the server variant of Windows 7, so it's the same issue. I'll remove this OS from the supported list in the install guide. Please upvote #98 if you would like to see it fixed.
