### ISSUE TITLE
Question: release plan or updates for mssql-cli?

### ISSUE THREAD

**Issue by kabirbaidhya** [dbcli/mssql-cli#150]
Hi,

I didn't see any tags published yet on [releases](https://github.com/dbcli/mssql-cli/releases) or [tags](https://github.com/dbcli/mssql-cli/tags) pages yet. But I just saw a new release `0.9.0` has been published to `pip` as previously I was using `0.8.0`.

I wanted to know what would be the best way to keep up with the recent releases and changes as I didn't see any changelogs or release history.

Thanks

**Comment by MrMeemus** [comment]
@kabirbaidhya, moving forward our releases will be tracked via github. This will include a changelot of all fixes and changes that went in. Also all of our releases will be announced on our twitter acccount: @sqldatatools

Thanks!
Ron

**Comment by kabirbaidhya** [comment]
Sure. Thanks..
