### ISSUE TITLE
"SELECT 1" on Azure SQL DB reports  incorrect result - "A query is already in progress for this editor session. Please cancel this query or wait for its completion"

### ISSUE THREAD

**Issue by sethusrinivasan** [dbcli/mssql-cli#157]
Connect to Azure SQL DB and issue a simple query SELECT 1

Client: Ubuntu 16.04 LTS

Outcome:
wrong results

Here is screenshot
![anotherqueryrunning](https://user-images.githubusercontent.com/3907049/35762750-3ba281d0-0851-11e8-81ff-5ddfbcd8d330.png)

**Comment by MrMeemus** [comment]
@sethusrinivasan , thanks for reporting! Both issues are tracked here: #103 and #95.

Will close this issue as a duplicate. Thanks again!
