### ISSUE TITLE
Possibility to disable auto-completion feature

### ISSUE THREAD

**Issue by mikedavem** [dbcli/mssql-cli#158]
Hi,

It could be good to get the possibility to disable auto-completion especially for environments that include thousand of objects. From my experience auto-completion feature from other tools like SSMS / RedGate etc .. may slow down our productivity in this specific context

Regards

**Comment by MrMeemus** [comment]
@mikedavem , thanks for reporting! this has been added in #162. We should have it in release 0.10.0 sometime next week.
