### ISSUE TITLE
Do not use a semicolon to end a multi-line query

### ISSUE THREAD

**Issue by pensivebrian** [dbcli/mssql-cli#175]
Currently when editing a multiline query, we use use a semicolon+<enter> to delineate the query should be executed.

Feedback from the MVP summit: in multiline query mode, users like to enter more that one statement, which are delineated by semicolons, so using a semicolon is a bad choice. We should consider using the 'GO' keyword to execute the query, which aligns with sqlcmd.

**Comment by ellbosch** [comment]
Tasks:
- [ ] tests for multiline
- [ ] update docs

Tests:
- [ ] toggling multiline
- [ ] use of semicolons (with, without, and mismatch)

No plans to support:
- Multi-line queries with multiple `GO`'s.

**Comment by ellbosch** [comment]
Turns out that a bug that's also affecting #393 may be blocking this effort. Various multiline queries are breaking, such as:
```
select 1
select 2;
go
```
