### ISSUE TITLE
Cannot login as Windows Authentication

### ISSUE THREAD

**Issue by illidanpc** [dbcli/mssql-cli#177]
Hello Experts, 

First, I greatly appreciate you guys made this amazing tool. The highlighted prompt is really helpful and beautiful. 

I just have a small question that I cannot find a parameter for Windows Authentication. I am not sure if it's my mistake to ask a so funny question. 

Please feel free to let me know if it's a non-supported scenario this moment. 

Regards,

**Comment by meeuw** [comment]
@pensivebrian told me: use the -E option to use windows/integrated authentication. If you configure kerberos, it should would on Linux/macOS as well.

**Comment by illidanpc** [comment]
It's Cool
