### ISSUE TITLE
Authentication to AD/LDAP-accounts

### ISSUE THREAD

**Issue by anton-johansson** [dbcli/mssql-cli#189]
I have a server with authentication through active directory. But I can't seem to login. If I were on Windows, I suppose it would work with the `--integrated` switch. But how would I do on a Linux platform?

**Comment by pensivebrian** [comment]
To use integrated authentication with mssql-cli on macOS or Linux, you first have to configure Kerberos using the [following steps](https://github.com/Microsoft/vscode-mssql/blob/master/KERBEROS_HELP.md). The steps are a bit tedious, but once configured, you should be able to connect using the `-E` or `--integrated` switch.

**Comment by chucker** [comment]
Do you mean `-I`? That yields:

>Integrated authentication not supported on this platform

Even if I previously ran `kinit`.

**Comment by ScriptMyJob** [comment]
Yeah, this is super annoying.  I am surprised that `mssql-cli` does not seem to support domain authentication on MacOS.  I seem to remember that I got this working in an earlier build (using `sqlcmd` on MacOS) but I am damned if I cannot figure it out now.  ¯\_(ツ)_/¯

There really should be a switch to handle AD Authentication that is not Azure.

**Comment by geoffclark** [comment]
Hi I cannot get mssql-cli to use my AD\LDAP account
It is correctly set up as I can use AD Authentication for SQL Operations Studio 2
Any help would be appreciated.

**Comment by djustins** [comment]
using RHEL7, also get:
Integrated authentication not supported on this platform

Even though i have a successful krb ticket

**Comment by pensivebrian** [comment]
We'll need to investigate this.

@MrMeemus - we should be using the -E switch for integrated auth to align with sqlcmd.

**Comment by MrMeemus** [comment]
There was a method that previously blocked integrated auth on non windows platforms due to the limitation in .Net Core prior. This has been fixed in #214 and will be slated for 0.15.0 release. Thanks all!
