### ISSUE TITLE
Any way to disable vertical output?

### ISSUE THREAD

**Issue by mithun-daa** [dbcli/mssql-cli#194]
First off, great job on this nifty little tool 👏 . 

I was doing some simple `selects` and looks like if there are too many columns, the tool defaults to using the vertical output even if it is not specified while connecting to the server.  Is there a way around this?

**Comment by amjith** [comment]
Yes. You can disable it in your config file. Check this line in your config file and set it to `never`. 

https://github.com/dbcli/mssql-cli/blob/master/mssqlcli/mssqlclirc#L29

You can find your config file at 

Linux: `~/.config/mssql-cli/config`
Windows:  `%USERPROFILE%\AppData\Local\dbcli\mssql-cli\config`

**Comment by mithun-daa** [comment]
Perfect! Thank you!
