### ISSUE TITLE
prevent Sql result from  piping to less command

### ISSUE THREAD

**Issue by sairamch04** [dbcli/mssql-cli#195]
I've installed as mentioned in [doc](https://github.com/dbcli/mssql-cli/blob/master/doc/installation/macos.md#installation-via-pip). Results of every query are being piped to less command. How can I stop from redirecting the output to `less` and show results in the same window

**Comment by amjith** [comment]
@sairamch04 You can adjust the behavior of the pager (less command) to suit your needs. 

Here's how you can change the behavior: https://github.com/dbcli/mssql-cli/blob/master/doc/troubleshooting_guide.md#default-pager-outputs-results-separate-from-main-console

If you uncomment the pager line in your config file it will default to using a sane configuration for the less command. If you just don't want to use a pager at all, you can change that line to say `pager = cat`. That will replace `less` with `cat` which will simply output the results in the same window without paging.

**Comment by sairamch04** [comment]
@amjith Thank you !. uncommented it

**Comment by twright-msft** [comment]
Thank you!  That was super annoying.  lol
