### ISSUE TITLE
How to install at UBUNTU 18 LTS?

### ISSUE THREAD

**Issue by ppKrauss** [dbcli/mssql-cli#204]
https://askubuntu.com/questions/1040028/how-to-install-mssql-cli-at-ubuntu-18-lts

**Comment by MrMeemus** [comment]
@ppKrauss, looks like we are missing a libicu60 depedency in the debian package. I'll have a PR out shortly.

**Comment by MrMeemus** [comment]
This has been fixed and released in pr #205. 

Running 

`sudo apt-get install mssql-cli`

Should resolve the new libicu60 dependency.

**Comment by ppKrauss** [comment]
Hi @MrMeemus, sorry to abandon: seems the correct solution solution (!), but I left Ubuntu 18 in favor of Ubuntu 16, as other peoble suggested. This issue must be tested/endorsed by other one.
