### ISSUE TITLE
Can not access for the first time for the login that needs to change the password

### ISSUE THREAD

**Issue by MasayukiOzawa** [dbcli/mssql-cli#206]
It is not possible to perform mssql-cli's first login using the logon created by the following query.
`
USE [master]
GO
CREATE LOGIN [logintest] WITH PASSWORD=N'<StrongP@ssw0rd12345>' MUST_CHANGE, 
DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
`

The following message will be output but mssql-cli will exit without prompting you to change the password.

> Error message: Login failed for user 'testlogin'.  Reason: The password of the account must be changed.

**Comment by MrMeemus** [comment]
@MasayukiOzawa , This behavior is expected from the CLI perspective. You'll have to log on as the server admin and alter the password prior to logging in.

https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-login-transact-sql?view=sql-server-2017
