### ISSUE TITLE
Is vertical output a default now? I get vertical output regardless.

### ISSUE THREAD

**Issue by BadSqlPro** [dbcli/mssql-cli#209]
I get vertical output regardless of whether or not I use the --auto-vertical-output at the time of the connection. I am using this right? I would like to have the horizontal scrolling unless I need the vertical scrolling. How do I get that?

**Comment by yualan** [comment]
Hi @BadSqlPro , what operating system are you using and which version number of mssql-cli?

**Comment by BadSqlPro** [comment]
I am using Windows 10 and Version 0.13.0 of mssql-cli

**Comment by pensivebrian** [comment]
IIRC, the default is behavior should only use vertical output if the query result text is wider than the window. If you want to enable horizontal scrolling on windows, you can:
1) Download less for windows (available [here](https://www.guysalias.tk/misc/less/)) and place it in your path (e.g. C:\Windows\system32)
2) Open the %localappdata%\dbcli\mssqlcli\config file
3) Locate the expand option and set `expand = never`
4) Restart mssql-cli and horizontal scrolling should work

We are investigating distributing less for windows and enabling horizontal scrolling as the default behavior. If this is something you'd like to see, please file a new issue, and we'll track the up votes!

**Comment by BadSqlPro** [comment]
Thanks for the update. Unfortunately, the binaries for Win32 at the link you provided are not extractable. I keep getting this error "Extracting less-530-win32-static-x86\less.exe 	Unknown compression method"
I even sent an email to the gentleman hosting the binaries. And since this is not some thing that is widely available and  easy to install, I think you should distribute the less utility and enable horizontal scrolling. Even if not as a default behavior but at least as an option at the connection prompt.

**Comment by pensivebrian** [comment]
@BadSqlPro -  Those file have a .7z extension, so you'll need to download [7-zip](https://www.7-zip.org/) to extract the files. After installing 7-zip, you should be able to right click on the less-530-win32-static-x86.7z file and select 7-Zip->Extract Here.

**Comment by BadSqlPro** [comment]
Oh Okay, will try that now. Thanks for the quick response.

**Comment by pensivebrian** [comment]
When Windows needs to run an executable, in this case less.exe, there are set of folder where Windows will search to find the executable. These folders that are search are set via the PATH environment variable. If you open a console and type `echo %PATH%` you can see which folders are included.

Since C:\Windows\system32 is already in the PATH by default, and I'm lazy, I just copy utilities like less.exe there. This way it's available system wide. Some might call this bad practice it's a system wide change. If you search the web, there are many ways to configure the PATH environment variable in a way that aligns with your sensibilities.

Hope that helps.

**Comment by BadSqlPro** [comment]
Oh Nice!!!! Thanks you very much for that shortcut! I was actually doing it
this way. Basically I extracted the fodler to C:\Program Files
(x86)\less-530-win32-static-x86 and after that I went to the Environment
Variables settings and included this folder. I think this should also work.
If not then I will copy the less.exe into the  C:\Windows\system32 folder.

Just that one Less.exe needs to be placed in the  C:\Windows\system32
folder or should I also place the lesskey.exe file as well?

**Comment by pensivebrian** [comment]
I did both.

**Comment by BadSqlPro** [comment]
Gotcha! I did that and I have not restarted the computer though but here is
the output after following all the steps you mentioned. So instead of
horizontal scrolling, there is a weird word wrapping going on. Check out
the screenshot.

**Comment by pensivebrian** [comment]
I'm not seeing any screenshots. Can you email me at b r o n e i l l @ m i c r o s o f t . c o m and I can help troubleshoot this?

**Comment by pensivebrian** [comment]
Closing - using #314 to track this

**Comment by Emmaka9** [comment]
> Hi @BadSqlPro , what operating system are you using and which version number of mssql-cli?

Hey can you help me out? I'm using ubuntu 18.04 and mssql-cli version 0.17.3
I also can't scroll horizontally, the output is by default vertical.

**Comment by pensivebrian** [comment]
@Emmaka9  - can you upgrade your mssql-cli version? In the latest version, we added logic to auto-detect if less.exe is available, and use it by default. This means that horizontal scrolling should just work after upgrading.

**Comment by Emmaka9** [comment]
@pensivebrian Thanks a lot, it works. 
1. Btw I guess horizontal scrolling comes with its own problem, which is if I scroll right to see the remaining part of the table, and then press q, only that part is visible to me.
Or if I press q while the first half is visible to me, then only the first half is visible to me.
I think if the table can be shown in two subsequent parts - one after the other, would be great, eg first the first part of the table from the beginning till depending on the screen size, then the remaining part right below that.

2. Can you provide me a link that explains what is less.exe?
