### ISSUE TITLE
Connection timeout when connect using ssh tunneling

### ISSUE THREAD

**Issue by nguymin4** [dbcli/mssql-cli#212]
Currently, I am able to connect to sql server using ssh tunneling using a nodejs package. However I cannot do the same with  mssql-cli. The command I tried is:
```
~ mssql-cli -S "tcp:localhost,1433" -d database -U username -P password
```

Error message:
```
Error message: Connection Timeout Expired.  
The timeout period elapsed during the post-login phase.  
The connection could have timed out while waiting for server to complete the login process and respond; 
Or it could have timed out while attempting to create multiple active connections.  
The duration spent while attempting to connect to this server was - 
[Pre-Login] initialization=51; handshake=767; 
[Login] initialization=4; authentication=8; 
[Post-Login] complete=14067;
```

**Comment by thorstenkampe** [comment]
Try `127.0.0.1` instead of localhost. That is a known issue with `mssql-cli` and also `sqlcmd`.

**Comment by nguymin4** [comment]
Thanks for your advice but I tried both before submitting the issue.

**Comment by andreif** [comment]
I get a login timeout when connecting to MSSQL via SSH tunnel and ODBC driver. It works fine connecting directly. Did you find a solution for your issue?

**Comment by nguymin4** [comment]
No, in the end  I used `https://www.npmjs.com/package/mssql` as CLI tool instead. A bit stupid that way but it works nevertheless.

**Comment by auther** [comment]
Me too the same issue without corrected yet.
