### ISSUE TITLE
Wrong table completion after database change

### ISSUE THREAD

**Issue by thorstenkampe** [dbcli/mssql-cli#221]
After switching databases with `use another_db` tab completion for tables - for instance after `select * from <TAB>` completes still from the tables of the previous database, not the current one.

Other members of the `dbcli` family complete tables from the current database.

**Comment by yualan** [comment]
I repro-ed this as well, team will investigate

**Comment by gdzwrk** [comment]
I am still experiencing this- if I connect using the `-d` option and specify my database, I receive proper table/view/FK completion suggestions.  If I omit the -d, by default it connects to the 'master' db.  If I then `use other_db` I am still only shown completion suggestions from master.

For now I am working around this by specifying the -d option when invoking the program.
