### ISSUE TITLE
Installation on Windows exiting with Error "not a supported wheel on this platform"

### ISSUE THREAD

**Issue by dheitmann88** [dbcli/mssql-cli#230]
Installation on Windows exiting with Error "not a supported wheel on this platform"

Installation Command and Error:
O:\Installationssourcen\MSSQL_CLI_preview>pip install mssql_cli-dev-latest-py2.p
y3-none-win_amd64.whl
mssql_cli-dev-latest-py2.py3-none-win_amd64.whl is not a supported wheel on this
 platform.

Python Version:
O:\Installationssourcen\MSSQL_CLI_preview>python -V
Python 3.7.1

Python Location:
O:\Installationssourcen\MSSQL_CLI_preview>where python
C:\Program Files (x86)\Python37-32\python.exe

Pip Version:
O:\Installationssourcen\MSSQL_CLI_preview>pip -V
pip 18.1 from c:\program files (x86)\python37-32\lib\site-packages\pip (python 3
.7)

Pip Location:
O:\Installationssourcen\MSSQL_CLI_preview>where pip
C:\Program Files (x86)\Python37-32\Scripts\pip.exe

OS Version:

O:\Installationssourcen\MSSQL_CLI_preview>ver
Microsoft Windows [Version 6.3.9600]

**Comment by dheitmann88** [comment]
We found a solution for it. But installing MSSQL-CLI or AzureDataStudio Notebooks without direct internet  connection is really awful, because you have to install many packages that are needed manually.

**Comment by MrMeemus** [comment]
@dheitmann88  what was your work around? what was your set up tools version? Regarding offline installs, that is the nature of most python packages now since we have to connect to the python repository. A alternative is you can install a virtual env after installation and zip up the contents of that folder and reactivate the virtualenv on other machines.

**Comment by dheitmann88** [comment]
@MrMeemus i checked which Python Packages i would be able to Install and got the package ai am able to install, after i manually installed all the prerequesite packages. so it finally workded. I will test the virtural env for sure, because installing it this way, wasn't a way to do it on multiple servers.

**Comment by pensivebrian** [comment]
@dheitmann88 - I think creating a windows installer with all dependencies packaged into the MSI would address this issue. I'm closing this, and tracking the windows install with #197.
