### ISSUE TITLE
Raw text output

### ISSUE THREAD

**Issue by anton-johansson** [dbcli/mssql-cli#231]
Is it possible to somehow output the result as raw text? For example, if I have a script that generates markdown, I'd like to avoid all the pipes and stuff that wraps the output. For example:

```
+----------------------------+
| (No column name)           |
|----------------------------|
| my markdown                |
| on multiple                |
| lines                      |
+----------------------------+
```

... would be nice to output as just:
```
my markdown
on multiple
lines
```

**Comment by MrMeemus** [comment]
@anton-johansson mssql-cli does not expose any config to change this setting as of now.

**Comment by anton-johansson** [comment]
Allright! Can we consider this a feature request? Obviously not a show-stopper for me, I'll be using the tool anyway. But it would be a nice-to-have feature.

**Comment by ellbosch** [comment]
@anton-johansson I think we have this supported now, please consult our docs for [non-interactive output options](https://github.com/dbcli/mssql-cli/blob/master/doc/usage_guide.md#outputting-a-query-execution-in-non-interactive-mode).

Closing this issue for now but please let me know if this doesn't fall within the scope of your request. Thanks!
