### ISSUE TITLE
is there a way to execute sql scrips in "onlliner" style

### ISSUE THREAD

**Issue by Strijd** [dbcli/mssql-cli#232]
Hi
I'm trying to run an sql query without having the prompt: 
`mssql-cli -S mighty  -U <some_user >-P <some_password>  bla.sql` 
Always fails with python exceptions
Is there a similar action ?

**Comment by MrMeemus** [comment]
@Strijd currently we only support the interactive experience. In the future we will look into adding piping support. Thanks!
