### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by EvanCarroll** [dbcli/mssql-cli#233]
It would be my advice to on Debian/Ubuntu systems to only ever support installs on Python3 which is shipped by default. To do this, you need to use

    pip3 install --user mssql-cli

Then what needs to happen in `./.local/bin/mssql-cli` is that you need to check (with `command -v python3 && python3 -m .... || python2 -m ...`) this will solve all of your problems on Debian/Ubuntu and not break anything else.

**Comment by EvanCarroll** [comment]
#234

**Comment by pensivebrian** [comment]
Sometime you can't control the version of python used, so only supporting python 3 is not yet an option. I'll leave it up to the end user to decide what pip version they want to run: pip or pip3. We have the rpm/apt installs for folks that don't want to use pip.

**Comment by EvanCarroll** [comment]
You only support distros that already include Python 3 as a default...
