### ISSUE TITLE
Using CTRL + D to shutdown mssql-cli. I receive a sql tools service message.

### ISSUE THREAD

**Issue by toddcarr** [dbcli/mssql-cli#235]
When i use CTRL + D to shutdown mssql-cli. I receive a sql tools service message.
"Sql Tools Service process was not shut down properly.Goodbye!"
Is this something i need to install? I have downloaded the zip file but i am not sure how to install it.

**Comment by MrMeemus** [comment]
Sql Tools service is the API server that is bundled with mssql-cli. Receiving this message could mean that shutdown was initiated mid execution against the server. It's not necessarily harmful, but you should verify that there isn't a SQL Tools service process running via task/process manager.

Does this occur every time? @toddcarr

**Comment by toddcarr** [comment]
Should i see this service running as a process or service? I do not see either one.

**Comment by toddcarr** [comment]
The problem does not occur everytime.

**Comment by pensivebrian** [comment]
Recently fixed this with PR #309
