### ISSUE TITLE
mssql-cli xubuntu 18.04 32 bit command not found and others problems

### ISSUE THREAD

**Issue by bcascino** [dbcli/mssql-cli#236]
Hi everyone, 
I installed mssql-cli via pip, both on python2 and python3 (using pip2 and pip3). The installation is successfull, but when I type mssql-cli this message comes out: command not found.
I thought it was a problem setting the PATH variable, but mssql-cli doesn't exists in any directories.
Can anyone help me? Is It a problem related to the fact that I have a 32-bit o.s.?

**Comment by MrMeemus** [comment]
@bcascino, we don't officially support Ubuntu 18 just yet, but you can give our Ubuntu 17 install steps a try. https://github.com/dbcli/mssql-cli/blob/master/doc/installation/linux.md#ubuntu-1704

if you prefer to use the pip route, can you share the output for "pip show mssql-cli"

**Comment by bcascino** [comment]
bart@bcascino-linux:~$ pip show mssql-cli
Name: mssql-cli
Version: 0.3
Summary: A way to run queries and execute commands against an MSSQL database.
Home-page: http://github.com/seanchon/mssql_cli/
Author: Sean Chon
Author-email: s@seanchon.com
License: MIT
Location: /home/bart/.local/lib/python2.7/site-packages
Requires: pymssql

**Comment by pensivebrian** [comment]
@bcascino - it looks like a very old version of mssql-cli is installed. Can you run pip with the upgrade command to pick up the latest version?

`$ pip install mssql-cli --upgrade`

If that still doesn't work, then we may have not published a wheel with the correct platform naming for x86, which we'll have to investigate. In which case, can you run the above command with the `--verbose` parameter to post the output?

**Comment by pensivebrian** [comment]
Closing this due to an out-of-date package being used. Please re-open if this issue persists.
