### ISSUE TITLE
Error install mssql-cli on fedora 29

### ISSUE THREAD

**Issue by limup** [dbcli/mssql-cli#237]
Hi,

I'm get error on Fedora 29.

No match for argument: mssql-cli
Error: Unable to find a match

How I resolve this?

**Comment by limup** [comment]
All,

I solved this problem.
Thanks for nothing. =)

**Comment by MrMeemus** [comment]
@limup, sorry for the delayed response. I'm curious to your fix if you can share it please.

**Comment by limup** [comment]
> @limup, sorry for the delayed response. I'm curious to your fix if you can share it please.

No problem, simply, I downloaded the [.rpm](https://github.com/dbcli/mssql-cli/tree/master#get-mssql-cli) package from the Fedora 26 version and executed the following commands:

```
sudo dnf update
sudo dnf install mssql-cli-dev-latest.rpm
```

I think the package does not exist in the Fedora 29 repository.

See ya.
