### ISSUE TITLE
Execute sql command on cli like -Q in sqlcmd

### ISSUE THREAD

**Issue by gseidel** [dbcli/mssql-cli#242]
Is there any way to execute a sql command directly from cli?

Like -Q option in sqlcmd

It would be nice to have something like `mssql-cli -Q 'SELECT * FROM table'` with output on stdout

**Comment by JamesCass** [comment]
I don't want to speak out of turn, but this is being addressed in Enhancement Issue #105 .

**Comment by ellbosch** [comment]
For the sake of scoping down the problem—my PR will address -Q without support for piping, but we will address piping in an upcoming update.
