### ISSUE TITLE
Ubuntu 19.04, libssl

### ISSUE THREAD

**Issue by anton-johansson** [dbcli/mssql-cli#252]
I upgraded to Ubuntu 19.04 the other day, and now I get this:
```
No usable version of the libssl was found
Error message: Connection request encountered an exception
```

Seems related to:
Microsoft/azuredatastudio#5134
Microsoft/vscode-python#5373
OmniSharp/omnisharp-vscode#3010

**Comment by byroniac** [comment]
Copied from other forum: I'm on Ubuntu 19.04 (Disco), but what seems to work is installing the Ubuntu 18.10 (Cosmic) libssl1.0.0 package, even though it's older than the bundled Disco package, from the link below. However, I don't know if this will introduce any system instability or issues. And I don't know if this will work on Pop! OS.
[https://packages.ubuntu.com/cosmic/libssl1.0.0](https://packages.ubuntu.com/cosmic/libssl1.0.0)

**Comment by anton-johansson** [comment]
Thanks, @byroniac, that worked.

What I did:
```
$ wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
$ sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
```

Both versions are now installed, and everything works as expected.

**Comment by funcelotwork** [comment]
> Thanks, @byroniac, that worked.
> 
> What I did:
> 
> ```
> $ wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
> $ sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
> ```
> 
> Both versions are now installed, and everything works as expected.

not found http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb

**Comment by byroniac** [comment]
@funcelotwork 
> not found http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb

They have dropped cosmic (18.10) packages since I posted that. You may try digging around on packages.ubuntu.com and see if you can find something else that will work for you, if you are having the problem. I am on 19.10 now but I have not even tried.

**Comment by ellbosch** [comment]
I'm afraid we don't support 19.04. We support up to 16.04 and have started testing an 18.04 release.

**Comment by zahid44** [comment]
use it from here it works somehow but unsure about security risks. Is there any potential risks?

wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb

**Comment by byroniac** [comment]
> use it from here it works somehow but unsure about security risks. Is there any potential risks?
> 
> `wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb`

Almost certainly with archived libssl files, I imagine. By definition, they are out of date.

**Comment by zahid44** [comment]
> > use it from here it works somehow but unsure about security risks. Is there any potential risks?
> > `wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb`
> 
> Almost certainly with archived libssl files, I imagine. By definition, they are out of date.

but cve has no report :S
