### ISSUE TITLE
The SQL Server instance returned an invalid or unsupported protocol version during login negotiation

### ISSUE THREAD

**Issue by jerome-peng** [dbcli/mssql-cli#253]
my sqlserver version is 2000, after installed myssql-cli, i get the below error:

c:\java\python>mssql-cli -S 192.168.99.1,3433 -U sa -d ranqi
Password:
Error message: The SQL Server instance returned an invalid or unsupported protocol version during login negotiation.

**Comment by noraj** [comment]
`Error message: The SQL Server instance returned an invalid or unsupported protocol version during login negotiation.` with `Microsoft SQL Server 2000 8.00.766.00; SP3a`, `Product_Version: 5.2.3790`.

**Comment by noraj** [comment]
What are supported versions?

**Comment by pensivebrian** [comment]
mssql-cli supports the same SQL Server versions supported by Microsoft, which is SQL Server 2008 and above. Previous versions such as SQL Server 2000 and 2005 are not supported. That said, mssql-cli should still work with SQL 2005.
