### ISSUE TITLE
Default location for mssqlclirc

### ISSUE THREAD

**Issue by andb0t** [dbcli/mssql-cli#265]
Hi everyone,

I'd like to put my custom `mssqlclirc` in a default location, such that `mssql-cli` picks it up automatically. I have searched the docs, but it's not there. I'm working on Ubuntu, so I thought it might be `~/.mssqlclirc` but that's not the case. I have to specify it explicitly. I'd like to avoid creating an alias to keep my environment clean. Is there a default location for the rc file?

Cheers!

**Comment by thorstenkampe** [comment]
The default configuration file on Linux is is called `config` and it's located in ` ~/.config/mssqlcli` where `~` stands for your home directory (`/home/<user>` in most cases).

**Comment by andb0t** [comment]
Thanks :) I'd like contribute by documenting this. Could you tell me where this should go? Then I can send a PR

**Comment by thorstenkampe** [comment]
Probably into `README.rst` because this is the landing point for anyone interested in `mssql-cli`.
