### ISSUE TITLE
how to Execute command and quit

### ISSUE THREAD

**Issue by denefer** [dbcli/mssql-cli#298]
hi all:

how to use mssql-cli command to show like "mysql -e 'show databases'"

**Comment by jeffhongxiao** [comment]
maybe related: https://github.com/dbcli/mssql-cli/issues/139#issuecomment-531748110

**Comment by pensivebrian** [comment]
This is one the roadmap, but there is not ETA adding this.

**Comment by pensivebrian** [comment]
Closing as a duplicate of https://github.com/dbcli/mssql-cli/issues/242, which will be used to track this issue.
