### ISSUE TITLE
virtual box ip address

### ISSUE THREAD

**Issue by rmpbklyn** [dbcli/mssql-cli#315]
unable to connect sql server on  vm virtual box with sql express.
it list ie8winxp\sqlexpress ssms
 the ip is internal in vm box and not known outside on the host machine

get error : Error message: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 25 - Connection string is not valid)

**Comment by ellbosch** [comment]
@rmpbklyn I think you may be able to resolve this if you configure the firewall to your SQL Server instance so that it allows your IP.

**Comment by ellbosch** [comment]
Closing for now, but please let me know if you run into more issues.
