### ISSUE TITLE
Update tar.gz source code

### ISSUE THREAD

**Issue by linuxunderground** [dbcli/mssql-cli#370]
Hi,

According to [https://pypi.org/project/mssql-cli/](https://pypi.org/project/mssql-cli/), last version of mssql-cli is 0.17.2 currently.

Newer versions were not tagged here : in this repository, last release is 0.15.0.
Can you provide last tar.gz source code here.

Thanks.

--
Vincent

**Comment by ellbosch** [comment]
Thanks @linuxunderground, we'll try to have this updated soon.

For now I recommend installation via `pip install mssql-cli`, if you can.

**Comment by linuxunderground** [comment]
> Thanks @linuxunderground, we'll try to have this updated soon.
> 
> For now I recommend installation via `pip install mssql-cli`, if you can.

@ellbosch : pip is not an option for me. My goal is to install mssql-cli with the Gentoo package manager and maintain [mssql-cli ebuild](https://github.com/linuxunderground/gentoo.overlay/tree/master/dev-db/mssql-cli).

**Comment by ellbosch** [comment]
We recently added support for source distributions with tar.gz in PyPI. Although you still may need to use `pip` to install it. Look for the tar.gz download [here](https://pypi.org/manage/project/mssql-cli/release/0.17.3/). Hopefully this can unblock you for now.

**Comment by linuxunderground** [comment]
@ellbosch 
Thank you for the 0.17.3 github tag and tar.gz source code release.
Gentoo ebuild updated :-)
