### ISSUE TITLE
Classes Under Wrong Module

### ISSUE THREAD

**Issue by PY84** [dbcli/mssql-cli#373]
https://github.com/dbcli/mssql-cli/blob/6b7c874343ebc0ce70fa01b399885628b5e9e9e5/mssqlcli/mssql_cli.py#L18

The "PromptSession" and "CompleteStyle" classes are found under the Shortcuts module, not prompt. The current import command will result in error message such as:
> ImportError: No module named prompt

This line 18 should be corrected to:

> from prompt_toolkit.shortcuts import PromptSession, CompleteStyle

Documentation reference:
[https://python-prompt-toolkit.readthedocs.io/en/stable/pages/reference.html#prompt_toolkit.shortcuts.PromptSession
](url)
[https://python-prompt-toolkit.readthedocs.io/en/stable/pages/reference.html#prompt_toolkit.shortcuts.CompleteStyle](url)

**Comment by ellbosch** [comment]
Good catch! Just created a PR to fix this.

Thanks for sharing :)
