### ISSUE TITLE
Publish latest release on currently supported Linux distributions

### ISSUE THREAD

**Issue by ellbosch** [dbcli/mssql-cli#383]
Some of our releases for Linux haven't been updated in years. We need to update these releases, operationalize the process where possible, and update release docs for how to do it.

Tagging thread in #139.

**Comment by ePaul** [comment]
Is this why following the [installation guide for Ubuntu](https://github.com/dbcli/mssql-cli/blob/master/doc/installation/linux.md#ubuntu) doesn't work (there is no package `mssql-cli` to install)?

**Comment by ellbosch** [comment]
Could be. Haven't had a chance to look yet, but plan to this month.

Moving forward we'll make sure to update all supported packages at a regular cadence.

**Comment by ellbosch** [comment]
We need to fix #101 to support Debian.
