### ISSUE TITLE
Install via pip3 doesn't work

### ISSUE THREAD

**Issue by ePaul** [dbcli/mssql-cli#385]
After failing to install this via apt, I tried to use pip to install mssql-cli on my Ubuntu 18.04.

```bash
sudo pip3 install mssql-cli
```
This installed something without any error, but then
```console
$ mssql-cli
/usr/bin/python: No module named mssqlcli
```

I tried installing `mssqlcli`, but that is https://github.com/rtrox/mssqlcli, and after that, I still get the same error.

It looks like the `mssql-cli` script is always calling the default `python` binary, which in my system is Python 2.

Installing via `pip2` seems to work. If this is python 2 only (or needs to be installed for the same python installation which `python` points to), this needs to be documented.

But I guess the installation could just create a script which uses the same python version which was used for installing it.

**Comment by ellbosch** [comment]
Apologies for your installation issues, we do in fact support Python 3.

Take a look at [this thread](https://stackoverflow.com/questions/37341614/modules-are-installed-using-pip-on-osx-but-not-found-when-importing). Looks like this can happen with multiple versions of Python installed.
