### ISSUE TITLE
Look into making autocomplete easier to understand

### ISSUE THREAD

**Issue by aashishkoirala** [dbcli/mssql-cli#398]
Thanks for this tool, really loving it. I have a question: when I am about to type in a command or query, I get these ghosted hints based on my command history - but I can't figure out how to actually select them - and so i end up having to type over them to entirety. Is there some key combination that I am unaware of?

For example, if in the past I have done a query called `SELECT * FROM Customers`, if i start typing `SELECT *`, it might show me that query in ghosted form - but I can't just tell it to just pick that query and save me the typing.

Thanks!

**Comment by ellbosch** [comment]
Select the right arrow key 🙂

I’ll look into seeing if we can make this more clear!

**Comment by aashishkoirala** [comment]
Wow, just saw this, thanks!

**Comment by maxwell-k** [comment]
I came across this today, it took some time to find that right arrow is what I'm looking for. Although the issue is closed it would be great if the documentation mentioned it.

Thank you for your work on mssql-cli!
