### ISSUE TITLE
Cannot login to server due to config location on MAC

### ISSUE THREAD

**Issue by yualan** [dbcli/mssql-cli#407]
On macOS, users cannot connect to a server with mssql-cli due to config location being in unexpected location. 

High priority.

**Comment by ellbosch** [comment]
@yualan please provide any repro steps and error messages here.

I've also validated that removing the config does not create this issue since mssql-cli creates a new config folder on startup if one isn't present.

**Comment by ellbosch** [comment]
Should hopefully be fixed with removal of sdist
