### ISSUE TITLE
Switching databases does not update intellisense

### ISSUE THREAD

**Issue by yualan** [dbcli/mssql-cli#408]
When I connect to a server in interactive mode and then switch to a database, intellisense is not updated to the new context.

**Comment by kstarzyk** [comment]
I experience same issue 
1. Connect to host
```
$ mssql-cli -U <user> -P <password> -S <host>
master >
```
2. Switching to different DB
```
master> use test_db;
Time: 0.252s
Commands completed successfully.
master>
```
3. Promp indicates "previous" db but context uses "new" db (`\lt` for instance returns tables from `test_db`);


If I start mssql-cli with `-d` flag it seems fine:
```
$ -U <user> -P <password> -S <host> -d test_db
test_db>
```
However `use` command still does not change prompt name

Version 1.0.0
