### ISSUE TITLE
mssql-cli broken on latest Windows update--'The system cannot find the file specified.'

### ISSUE THREAD

**Issue by G0erman** [dbcli/mssql-cli#437]
I just connected to a server successful with some specific port:

`mssql-cli -S server_name,port -U user -P password`

But when I try to launch some query, I get the next message:

```
XXX> select 4+4;
Time: 0.451s
The system cannot find the file specified.
```

mssql-cli version: 0.18.1

**Comment by altafub** [comment]
I have the same issue on new servers. 

`master> select name from sys.databases
Time: 0.555s
The system cannot find the file specified.`

I am using pip install command to install the utility. Tried to install 0.18.0 on the same machine. It uninstalled 0.18.1 first and installed the supplied version. But that doesn't seem to help.

**Comment by jvillegas74** [comment]
I have the same issue. whatever I do I get "The system cannot find the file specified."

**Comment by ellbosch** [comment]
@G0erman, @altafub, and @jvillegas74: what machine is everyone on? How was mssql-cli installed?

**Comment by jvillegas74** [comment]
This is Windows 10

**Comment by ellbosch** [comment]
> This is Windows 10 (x64). Running on a Surface Pro 4. Aso the same on a Dell XPS 15

Thanks. What version of Python are you using? And do you experience the same issue on 0.18.0?

You may install a prior version by calling `python -m pip install mssql-cli==0.18.0`.

**Comment by jvillegas74** [comment]
just tried with 0.18.0 and the same as the latest 0.18.1

Using Phyton 3.8.2

**Comment by ellbosch** [comment]
Can you call `mssql-cli --version` and let me know what you get? Thanks @jvillegas74, I want to rule out that your machine isn't still installing an older version, which has happened before.

**Comment by jvillegas74** [comment]
I have tried with 0.18.1 (latest) and 0.18.0 as well as 0.17.0 . All of them same output

Anyway here is the output

Installing collected packages: mssql-cli
  Attempting uninstall: mssql-cli
    Found existing installation: mssql-cli 0.17.0
    Uninstalling mssql-cli-0.17.0:
      Successfully uninstalled mssql-cli-0.17.0
Successfully installed mssql-cli-0.18.0

C:\WINDOWS\system32>mssql-cli --version
Version: 0.18.0

**Comment by jvillegas74** [comment]
@ellbosch Any workaround you might recommend ?

**Comment by ellbosch** [comment]
Unfortunately I'm still unable to repro this issue. However—it would help a lot if you could post your log file here (and a clean set of logs too would be great!).

The logfile is located at `%LOCALAPPDATA%\dbcli\mssqlcli\mssqlcli`.

**Comment by jvillegas74** [comment]
[mssqlcli.log](https://github.com/dbcli/mssql-cli/files/4351817/mssqlcli.log)

Here is a clean log

**Comment by ellbosch** [comment]
Thanks @jvillegas74. Some more questions:
* Did mssql-cli used to work for you or has it always been like this?
* Are you using a standard command line or the Linux Subsystem?
* Is there any other error message in the stack trace that could help for debugging?

**Comment by jvillegas74** [comment]
@ellbosch I have installed for first time.
I am using standard command line CMD (as regular user and as Administrator)
![image](https://user-images.githubusercontent.com/15475995/77016774-7426ea00-6957-11ea-8ec6-e402f2922a96.png)

**Comment by ellbosch** [comment]
Thanks. Can you please return the output for `which mssql-cli`? Perhaps there's a path issue...

**Comment by jvillegas74** [comment]
Probably
![image](https://user-images.githubusercontent.com/15475995/77017304-e64bfe80-6958-11ea-8ab0-90c626632ac5.png)
not a Pyton expert

**Comment by ellbosch** [comment]
> Probably
> ![image](https://user-images.githubusercontent.com/15475995/77017304-e64bfe80-6958-11ea-8ab0-90c626632ac5.png)
> not a Pyton expert

Sorry I meant `where mssql-cli`. My apologies!!

**Comment by jvillegas74** [comment]
here
![image](https://user-images.githubusercontent.com/15475995/77017451-4e9ae000-6959-11ea-92d3-66c6e018ece4.png)

**Comment by ellbosch** [comment]
Thanks @jvillegas74. This doesn't look like a path issue.

Are you able to query this database with another tool? I want to ensure this error message is exclusive to mssql-cli and not an issue with your SQL Server instance.

If you don't have another tool installed, I'd recommend [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15).

**Comment by jvillegas74** [comment]
yes. I can connect to my localhost running SQL 2019 using SQLCMD, ADS and SSMS with no problem

**Comment by ellbosch** [comment]
Hmmm... are you possibly using Windows Auth instead of SQL @jvillegas74?

**Comment by jvillegas74** [comment]
same thing using SQL Auth
![image](https://user-images.githubusercontent.com/15475995/77019349-31691000-695f-11ea-98c5-268a8c59affa.png)

**Comment by jvillegas74** [comment]
No problems with SQLCMD
![image](https://user-images.githubusercontent.com/15475995/77019486-6ecd9d80-695f-11ea-87b4-bf928a4a6977.png)

**Comment by ellbosch** [comment]
I wish I could repro this :( I'm so sorry this is happening, thanks for all of your help @jvillegas74.

Let me know if you're unblocked by using a really old version, say 0.15.0. If that still doesn't work then there's a good chance we've had this bug since the beginning. I'll keep digging in the meantime.

**Comment by jvillegas74** [comment]
Is not the day today ! . this is after installing 0.15.0
![image](https://user-images.githubusercontent.com/15475995/77019930-d46e5980-6960-11ea-9fe7-e05b919de8e8.png)

**Comment by ellbosch** [comment]
This info still helps in any case! Good to know this bug exists, thanks @jvillegas74.

**Comment by altafub** [comment]
We use Windows 2016 ami provided by AWS. And 0.18.1 doesn't work with ami released after 11th Feb.
So this has to be a windows update thing.

**Comment by ellbosch** [comment]
> We use Windows 2016 ami provided by AWS. And 0.18.1 doesn't work with ami released after 11th Feb.
> So this has to be a windows update thing. @ellbosch

Interesting... @altafub are you also using a localhost db like @jvillegas74?

**Comment by ellbosch** [comment]
Confirmed this is caused by latest Windows update—I'm now able to repro this.

**Comment by jvillegas74** [comment]
I can add that I just installed on a new Win 2016 Server (Azure VM) and got the same error connecting to localhost and remote server

**Comment by jvillegas74** [comment]
Please share here or by email when the fix is available. looking forward to talk and demo about mssql-cli in my next presentation

**Comment by ellbosch** [comment]
> @ellbosch Please share here or by email when the fix is available. looking forward to talk and demo about mssql-cli in my next presentation

Will do @jvillegas74, fixing this bug is our top priority.

**Comment by ellbosch** [comment]
Looks like one of our [dependencies](https://github.com/pallets/click/issues/1501) is the culprit. I'll update the thread when new official bits are out.

**Comment by ellbosch** [comment]
The fix is out! @jvillegas74 @altafub thanks so much for your help :)

**Comment by altafub** [comment]
@ellbosch thanks a ton for the prompt response and fixing this. I can confirm this is working now.

**Comment by jvillegas74** [comment]
Thanks @ellbosch for the quick response !! is working great now

**Comment by jvillegas74** [comment]
thanks @ellbosch for the quick response. it works great !! 
which will be the right way to update ?

Alse the installation guide link  from the doc is broken
https://docs.microsoft.com/en-us/sql/tools/mssql-cli?view=sql-server-ver15

**Comment by ellbosch** [comment]
@jvillegas74 you may view installation docs here: https://github.com/dbcli/mssql-cli/tree/master/doc/installation

Thanks for letting us know about the docs!

**Comment by ellbosch** [comment]
The Microsoft Docs page is now fixed.
