### ISSUE TITLE
Python3 install installs wrapper calling python instead of python3

### ISSUE THREAD

**Issue by thorstenkampe** [dbcli/mssql-cli#451]
```
> sudo pip3 install mssql-cli
Collecting mssql-cli
  Using cached mssql_cli-0.18.2-py2.py3-none-manylinux1_x86_64.whl (43.4 MB)
Requirement already satisfied: [...]
[...]
Installing collected packages: mssql-cli
Successfully installed mssql-cli-0.18.2
```
```
> mssql-cli
/usr/local/bin/mssql-cli: Zeile 16: python: command not found
```
```
> grep python /usr/local/bin/mssql-cli
[...]
16:python -m mssqlcli.main "$@"
```
All other Python scripts installed via pip in /usr/local/bin refer to python3[.8].

**Comment by ellbosch** [comment]
@thorstenkampe what OS are you using to install mssql-cli?

**Comment by thorstenkampe** [comment]
@ellbosch I'm using Ubuntu 18.04

**Comment by ellbosch** [comment]
As of fairly recently we've published a version to apt-get that should work on Ubuntu 18.04. Best to uninstall mssql-cli first using `pip3 uninstall mssql-cli` and then follow these instructions:
```
# Installs mssql-cli from Packages.Microsoft
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

# Use for pulling from prod channel
RUN apt-add-repository https://packages.microsoft.com/ubuntu/18.04/prod

RUN apt-get update
RUN apt-get install -y mssql-cli

# Installs missing requirements
RUN apt-get install -y -f
```

Please let me know if this resolves your problem.

**Comment by thorstenkampe** [comment]
Sorry, the packages creates
* its own root directory (/mssql-cli)
* brings its own Python (Python 3.6) 
* does not at all integrate with existing Python (3.7.5)
* does not work
```
[...]
  File "/mssql-cli/lib/python3.6/site-packages/terminaltables/terminal_io.py", line 3, in <module>
    import ctypes
  File "/mssql-cli/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

**Comment by ellbosch** [comment]
Interesting bug there... can you pass along the response you get for calling `arch` in the command line?

FYI—we bundle our own Python version with Ubuntu to prevent potential conflicts with Python dependencies downloaded elsewhere. There may be some issues if you attempt a purist Python installation on Linux.

**Comment by thorstenkampe** [comment]
I have to correct myself: the distribution is not 18.04 but 19.10, the latest version of Ubuntu.

**Comment by ellbosch** [comment]
Sorry @thorstenkampe, we don't support 19.10 at this time. Closing this issue.
