### ISSUE TITLE
Option to specify location of configuration directory

### ISSUE THREAD

**Issue by cjvirtucio87** [dbcli/mssql-cli#454]
Hi,

Running `mssql-cli` causes it to [create a config directory](https://github.com/dbcli/mssql-cli/blob/0.18.1/mssqlcli/main.py#L33). Unfortunately, it [appears to do so on the home directory](https://github.com/dbcli/mssql-cli/blob/0.18.1/mssqlcli/config.py#L17). This is a little troublesome for us, as we run our capabilities on [OpenShift](https://www.openshift.com/), whose [guidelines](https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html) require us to support arbitrary users. Being able to run `mssql-cli` _without_ being tied to any given user would simplify deployment for us.

Can an option to specify the location of the configuration directory be added?

**Comment by ellbosch** [comment]
Thanks for the suggestion, however I'm still a bit confused with the exact issue for using a home directory. mssql-cli will create a new config if one isn't found, wouldn't this resolve your issue? Forgive me if I'm not understanding the issue perfectly 🙂

**Comment by cjvirtucio87** [comment]
Hi, thanks for the response. `OpenShift` assigns a dynamically generated user to each container that runs on the cluster _at runtime_.  We can't rely on any particular user, nor can we rely on leveraging the user's home directory. Instead, (per their guidelines) we set group ownership on the executables in an arbitrary folder (usually something like `/opt/app`) to the _root group_ (gid `0`), so that any dynamically generated user can run them (each generated user is part of the _root group_).
