### ISSUE TITLE
Login failed for user 'sa'

### ISSUE THREAD

**Issue by catchsandy** [dbcli/mssql-cli#455]
Not able to connect to docker sql server express container thru mssql-cli on mac system
using this command to login mssql-cli -S localhost -U sa -d master -P password

but everytime it is throwing the same error
Login failed for user 'sa'
any input will be highly appreciated

**Comment by ellbosch** [comment]
Sounds like the password is incorrect 🙂 maybe try surrounding the password in quotes?

**Comment by ellbosch** [comment]
Closing this but please reach out if you're still running into problems.
