### ISSUE TITLE
mssql-cli install fails: Writing more data than expected (66158224 > 66153108)

### ISSUE THREAD

**Issue by orionJag** [dbcli/mssql-cli#456]
Hi
         I know this was working few days back on the newly created Ubuntu 16.04, but currently I'm getting the following msg 

  Err:1 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 mssql-cli all 0.18.1-1 
          writing more data than expected (66158224 > 66153108)
 E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/m/mssql-cli/mssql-cli-dev-latest.debwriting more data than expected (66158224 > 66153108)

E: Unable to fetch some archives, may be run apt-get update or try with --fix-missing? 

The following were the steps followed for the install of mssql-cli
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo apt-add-repository https://packages.microsoft.com/ubuntu/16.04/prod
sudo apt-get update
sudo apt-get install mssql-cli

Though I tried issuing apt-get update and  --fix-missing, no luck so far. 

Need help, on what I am missing and how to have this resolved.  

Appreciate the help in advance. 

Thanks

**Comment by gvanderclay** [comment]
We are also seeing this on our project

**Comment by orionJag** [comment]
Good to hear, I'm not the only one. 

In case, you do not want to be stuck until this's resolved, I used the following tool - no issues here. 

https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15

Thought it would help.

**Comment by gvanderclay** [comment]
@orionJag Thanks for the reccomendation. We're getting around the issue by using pip to install mssql-cli.
https://github.com/dbcli/mssql-cli/blob/master/doc/installation/pip.md#install-ubuntu--debian--mint

**Comment by ellbosch** [comment]
This is strange... has this just started to pop up today for you all? Thanks for reporting this.

Does calling `sudo apt-get install -f` fix the problem?

**Comment by ellbosch** [comment]
We had a server-side issue, this appears to be fixed now. Please let me know if you're able to install again using apt-get.

**Comment by ellbosch** [comment]
Closing, this appears to be fixed now.

**Comment by gvanderclay** [comment]
Sweet. Thanks for being responsive @ellbosch 💯
