### ISSUE TITLE
Minor typo in  mssql-cli/doc/installation/linux.md

### ISSUE THREAD

**Issue by pjwelsh** [dbcli/mssql-cli#489]
https://packages.microsoft.com/config/cenots/8/prod.repo
should be:
https://packages.microsoft.com/config/centos/8/prod.repo

Note the "centos" is misspelled.

**Comment by pjwelsh** [comment]
Oops, did not type in the original typo - had the correction twice.

**Comment by pensivebrian** [comment]
Fixed with PR #485.
