### ISSUE TITLE
add support to connect via system managed identity

### ISSUE THREAD

**Issue by darrenpricedcww** [dbcli/mssql-cli#495]
unable to find any switch or guidance how to connect to sql utilising a system manged identity.

eg a VM with a system managed identity that has been provide access to the the sql server should be able to connect without need to supply credentials

**Comment by jamesbannan** [comment]
@yualan Any thoughts on this one? I've got this exact situation with a customer where we have to use username/password authentication from `mssql-cli` on an Azure VM with an assigned MSI. It would be great (not to mention more secure) to use the MSI.

**Comment by darrenpricedcww** [comment]
using sqlcmd instead
