### ISSUE TITLE
PyPI Version of mssql-cli (v1.0.0) dependency list breaks mercurial (hg) [and probably other packages]

### ISSUE THREAD

**Issue by danieldjewell** [dbcli/mssql-cli#561]
The version of `mssql-cli` published on PyPI breaks several other packages (notably `mercurial`/hg) by installing the `enum34` package. At least on Python 3.10 `enum` is a core/built-in... so that dependency breaks core Python functionality. 

This appears to have been fixed in #509 (which was committed quite awhile ago....)  ... specifically: 

https://github.com/dbcli/mssql-cli/pull/509/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R42

https://github.com/dbcli/mssql-cli/blob/b874d0aa09fb1e379100c8ad1409d38c408fe341/setup.py#L42

However, these changes were never released to PyPI ... 

@pensivebrian Are you still with Microsoft?

@alanrenmsft @Charles-Gagnon @kburtram @kisantia I recognize that this isn't your project, but since you seem to be pretty active in the SQL Server space, perhaps you might be able to escalate/refer/tell someone about this? I suspect there are quite a few people out there who have installed this only to find that it ends up breaking things.

**Comment by erinstellato-ms** [comment]
Hi @danieldjewell - thank you for bringing this to our attention.  mssql-cli is on the path to deprecation, and it will be replaced by the new sqlcmd (https://learn.microsoft.com/en-us/sql/tools/sqlcmd/go-sqlcmd-utility?view=sql-server-ver16)) once it becomes generally available.  We can push the latest release of mssql-cli to PyPI, but we recommend exploring the new sqlcmd as a replacement for mssql-cli.  We are actively in development for the new sqlcmd, and would love to hear feedback (requests, issues): (https://github.com/microsoft/go-sqlcmd/issues).

**Comment by azinsharaf** [comment]
@erinstellato-ms Is go-sqlcmd an open source project?

**Comment by erinstellato-ms** [comment]
@azinsharaf Yes, go-sqlcmd is an open source project, as noted in the readme: https://github.com/microsoft/go-sqlcmd

**Comment by azinsharaf** [comment]
> @azinsharaf Yes, go-sqlcmd is an open source project, as noted in the readme: https://github.com/microsoft/go-sqlcmd

thanks, looking forward to using it.

**Comment by danieldjewell** [comment]
Awesome! Thank you - I see that the deprecation notice was added the day after I opened this issue (3021193c65e942cf30e0b006cc3b88445e966373) - that helps clarify things! 

Looking forward to trying out the new go-sqlcmd
