### ISSUE TITLE
--help text mentions postgres

### ISSUE THREAD

**Issue by DaveDustin** [dbcli/mssql-cli#92]
If you display help information, the descriptive information for -U states

>   -U, --username TEXT     Username to connect to the **postgres** database.

**Comment by MrMeemus** [comment]
@DaveDustin Thanks for find! We will have this fixed in our next release.

**Comment by pensivebrian** [comment]
Fixed with commit beeb296d57dfea40a7eac6921ab383a433a2ef2a.

**Comment by MrMeemus** [comment]
Fix has been released in 0.8.0. Thanks!
