### ISSUE TITLE
Better prompt option, like $_ in cmd.exe

### ISSUE THREAD

**Issue by MightyPen** [dbcli/mssql-cli#94]
In Windows cmd.exe, by default the prompt is pushed far from the left edge, by display of the directory path. This is awkward and ugly to the eye, as commands of modest length must wrap to the next line.
Not enough people know about the $_ option a cmd.exe window (or in System Environment variables), as in:

> set Prompt=[$P\]$_$+$G$G$S

The above 'set' command changes the prompt from a single line to a double line, due to $_.  Compare the next two prompt examples (1 = single line, 2 = double line):

1.
C:\users\genemi\MyFunDirectory>echo Hello World

2.
[C:\users\genemi\MyFunDirectory\]
>> echo Hello World

So, please enable prompt configuration so commands can start near the left edge, while still displaying the database name or whatever in the preceding line.  :-) 

Thanks. GeneMi @ microsoft. com  (Tuesday  2017/12/12  18:44pm  Redmond time)

**Comment by pensivebrian** [comment]
This is fixed in the latest 0.10.0 version.

To achieve a prompt that starts on a newline, you can add the following to config line to your config file. On Windows, the path to the config file is `%APPLOCAL%\dbcli\mssqlcli\config`.

`prompt = '\d\n> '`

**Comment by MightyPen** [comment]
Thanks!
