### ISSUE TITLE
add support for ODBC connections

### ISSUE THREAD

**Issue by mi-hol** [dbcli/mssql-cli#96]
Please add support for ODBC connections. This would make this great tool even much more useful!

Many companies migrate from ORACLE now to SQLserver, a cli  that works with both 'worlds' would ease the training burden, enable a steep learning curve and would help in general by making the migration process more smoothly.

**Comment by pensivebrian** [comment]
Thanks for the feedback mi-hol. It would be nice to support ODBC connections, however we are currently focused on making mssql-cli work well with the [SqlToolService ](https://github.com/Microsoft/sqltoolsservice) and SQL Server. ODBC support is not on our road map.
