### ISSUE TITLE
Python 2 or 3?

### ISSUE THREAD

**Issue by gerardog** [dbcli/mssql-cli#97]
Installation guide does not specify which python version should I use. 

Thanks

**Comment by amjith** [comment]
It works on both. Make sure you're using python 2.7 or above.

**Comment by Jaxelr** [comment]
Thanks, ideally the installation guide could specify it?

**Comment by pensivebrian** [comment]
Yes, this should be in the installation guide. I've add a note about this with commit 207cc9a31be5a6a1f037edfcf405e39724e3b680. Thanks for reporting.
