### ISSUE TITLE
Minor update to Installation Guide

### ISSUE THREAD

**Issue by AirborneGeek** [dbcli/mssql-cli#99]
For the pip installation on Windows, the command box needs to be running as admin for the installation to complete; this isn't mentioned in the docs (just says "open a command prompt").

**Comment by pensivebrian** [comment]
If you installed python to your program files directory, then yes, admin permission are required. A note about this in the docs would be helpful. I'll make a doc update later today.

**Comment by pensivebrian** [comment]
Updated the install guide with commit 0092acd11068ff6f74577d739eb5e8fed391e08a
